let employees1 = [{ id: 101, name: "Rahul Gandhi", sal: 45000 },
{ id: 102, name: "Sonia Gandhi", sal: 55000 },
{ id: 103, name: "Priynka Gandhi", sal: 65000 },
{ id: 104, name: "Robert Gandhi", sal: 75000 }
]
let employees = [{ "id": 1, "name": "Effie", "sal": "Rupiah" },
{ "id": 2, "name": "Tory", "sal": "Peso" },
{ "id": 3, "name": "Dian", "sal": "Rupiah" },
{ "id": 4, "name": "Marthe", "sal": "Peso" },
{ "id": 5, "name": "Andrej", "sal": "Yuan Renminbi" },
{ "id": 6, "name": "Katrine", "sal": "Yuan Renminbi" },
{ "id": 7, "name": "Hetty", "sal": "Yuan Renminbi" },
{ "id": 8, "name": "Di", "sal": "Cordoba" },
{ "id": 9, "name": "Levey", "sal": "Rupiah" },
{ "id": 10, "name": "Immanuel", "sal": "Rupee" },
{ "id": 11, "name": "Austina", "sal": "Lek" },
{ "id": 12, "name": "Stephan", "sal": "Lek" },
{ "id": 13, "name": "Janifer", "sal": "Yuan Renminbi" },
{ "id": 14, "name": "Magdaia", "sal": "Yuan Renminbi" },
{ "id": 15, "name": "Arnold", "sal": "Zloty" },
{ "id": 16, "name": "Nobe", "sal": "Dollar" },
{ "id": 17, "name": "Kriste", "sal": "Real" },
{ "id": 18, "name": "Bertram", "sal": "Yuan Renminbi" },
{ "id": 19, "name": "Hersch", "sal": "Real" },
{ "id": 20, "name": "Alec", "sal": "Yuan Renminbi" },
{ "id": 21, "name": "Karalynn", "sal": "Rupiah" },
{ "id": 22, "name": "Berton", "sal": "Krona" },
{ "id": 23, "name": "Gabrielle", "sal": "Peso" },
{ "id": 24, "name": "Debbi", "sal": "Dollar" },
{ "id": 25, "name": "Amanda", "sal": "Lev" },
{ "id": 26, "name": "Brewer", "sal": "Peso" },
{ "id": 27, "name": "Marget", "sal": "Yuan Renminbi" },
{ "id": 28, "name": "Nelly", "sal": "Rupiah" },
{ "id": 29, "name": "Tamra", "sal": "Rupiah" },
{ "id": 30, "name": "Arluene", "sal": "Yuan Renminbi" },
{ "id": 31, "name": "Nance", "sal": "Ruble" },
{ "id": 32, "name": "Terza", "sal": "Rial" },
{ "id": 33, "name": "Sloan", "sal": "Peso" },
{ "id": 34, "name": "Cathi", "sal": "Euro" },
{ "id": 35, "name": "Dougy", "sal": "Real" },
{ "id": 36, "name": "Ezri", "sal": "Yuan Renminbi" },
{ "id": 37, "name": "Hyacinthia", "sal": "Rupiah" },
{ "id": 38, "name": "Briano", "sal": "Ringgit" },
{ "id": 39, "name": "Hilliary", "sal": "Dollar" },
{ "id": 40, "name": "Nyssa", "sal": "Kwacha" },
{ "id": 41, "name": "Hilliary", "sal": "Peso" },
{ "id": 42, "name": "Jesus", "sal": "Zloty" },
{ "id": 43, "name": "Allister", "sal": "Bolivar" },
{ "id": 44, "name": "Fielding", "sal": "Peso" },
{ "id": 45, "name": "Caddric", "sal": "Somoni" },
{ "id": 46, "name": "Van", "sal": "Rupiah" },
{ "id": 47, "name": "Averil", "sal": "Dollar" },
{ "id": 48, "name": "Brander", "sal": "Euro" },
{ "id": 49, "name": "Billy", "sal": "Yuan Renminbi" },
{ "id": 50, "name": "Simeon", "sal": "Ruble" },
{ "id": 51, "name": "Levon", "sal": "Rial" },
{ "id": 52, "name": "Ibrahim", "sal": "Sol" },
{ "id": 53, "name": "Lilas", "sal": "Som" },
{ "id": 54, "name": "Dex", "sal": "Euro" },
{ "id": 55, "name": "Easter", "sal": "Dollar" },
{ "id": 56, "name": "Normie", "sal": "Pula" },
{ "id": 57, "name": "Valera", "sal": "Som" },
{ "id": 58, "name": "Donal", "sal": "Peso" },
{ "id": 59, "name": "Raff", "sal": "Rupiah" },
{ "id": 60, "name": "Rivalee", "sal": "Yuan Renminbi" },
{ "id": 61, "name": "Stephanie", "sal": "Peso" },
{ "id": 62, "name": "Donaugh", "sal": "Peso" },
{ "id": 63, "name": "Marve", "sal": "Koruna" },
{ "id": 64, "name": "Eldredge", "sal": "Euro" },
{ "id": 65, "name": "Barbi", "sal": "Yuan Renminbi" },
{ "id": 66, "name": "Tildy", "sal": "Yen" },
{ "id": 67, "name": "Dara", "sal": "Ariary" },
{ "id": 68, "name": "Jaquith", "sal": "Yuan Renminbi" },
{ "id": 69, "name": "Tad", "sal": "Tenge" },
{ "id": 70, "name": "Lizzie", "sal": "Peso" },
{ "id": 71, "name": "Egan", "sal": "Zloty" },
{ "id": 72, "name": "Gabriella", "sal": "Sol" },
{ "id": 73, "name": "Nev", "sal": "Peso" },
{ "id": 74, "name": "Kristofor", "sal": "Euro" },
{ "id": 75, "name": "Finn", "sal": "Rupiah" },
{ "id": 76, "name": "Adolphe", "sal": "Zloty" },
{ "id": 77, "name": "Ingunna", "sal": "Yuan Renminbi" },
{ "id": 78, "name": "Benedetto", "sal": "Pound" },
{ "id": 79, "name": "Trumaine", "sal": "Rupiah" },
{ "id": 80, "name": "Milissent", "sal": "Dollar" },
{ "id": 81, "name": "Gilberte", "sal": "Dollar" },
{ "id": 82, "name": "Shena", "sal": "Denar" },
{ "id": 83, "name": "Jeanie", "sal": "Dinar" },
{ "id": 84, "name": "Kelley", "sal": "Rupiah" },
{ "id": 85, "name": "Darrin", "sal": "Rupiah" },
{ "id": 86, "name": "Hildegarde", "sal": "Krona" },
{ "id": 87, "name": "Tine", "sal": "Rupee" },
{ "id": 88, "name": "Fawn", "sal": "Zloty" },
{ "id": 89, "name": "Garv", "sal": "Peso" },
{ "id": 90, "name": "Lamont", "sal": "Dollar" },
{ "id": 91, "name": "Orsola", "sal": "Yuan Renminbi" },
{ "id": 92, "name": "Cassaundra", "sal": "Quetzal" },
{ "id": 93, "name": "Herbert", "sal": "Rupiah" },
{ "id": 94, "name": "Shellysheldon", "sal": "Yuan Renminbi" },
{ "id": 95, "name": "Benoite", "sal": "Manat" },
{ "id": 96, "name": "Parry", "sal": "Hryvnia" },
{ "id": 97, "name": "Muire", "sal": "Euro" },
{ "id": 98, "name": "Mariette", "sal": "Peso" },
{ "id": 99, "name": "Ermina", "sal": "Yuan Renminbi" }]
function displayData() {
    let rows = ""

    employees.forEach((emp) => {
        rows = rows + `<tr> 
                             <td> ${emp.id}</td>
                              <td> ${emp.name}</td>
                             <td> ${emp.sal}</td>
                        </tr>`
    })
    document.getElementById('tdata').innerHTML = rows

}
